:lipstick: Updated and improved mobile support for UI
JamFactoryApp/jamfactory-static pull request #3
Opened 2021-11-18 13:19 UTC by Pallemann

2021-11-19 09:37 UTC, exp625 requested changes
Looks good to me. I would only provide more space to the bottom of the site to make space for a footer. Maybe you could already add a link to imprint.html and the github project.

See inline comments.

2021-11-19 09:37 UTC, exp625 commented on .gitignore
> +package-lock.json
Please don't ignore the package-lock.json as it is needed for automated docker builds

2021-11-19 09:37 UTC, exp625 commented on .gitignore
> +package-lock.json
Also restore the delete file pls

2021-11-20 00:05 UTC, Pallemann commented
Added the footer with links to Github and the imprint.
.gitignore was fixed as well.

2021-11-20 14:47 UTC, exp625 commented on src/index.html
> +            <a href="/imprint.html" target="_blank" class="h-100 impressum">Impressum</a>
I would remove the ``target="_blank"`` from the link to the imprint. The imprint should not open a new tab.
However with the current  ``transition: 0.5s;`` for everything this looks kinda strange.

See updated Readme for information about untracked files.

2021-11-28 18:30 UTC, exp625 approved these changes

2021-11-28 18:30 UTC, merged